version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "9000:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: Drs_2022
      MYSQL_DATABASE: drsdb
    volumes:
      - ./DB/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql

  engine:
    build: 
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - ./:/usr/src/app/

  ui:
    image: "node:18.12.1"
    depends_on:
      - engine
    working_dir: /home/node/app
    links:
      - engine
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    volumes:
      - ./UI:/home/node/app

volumes:
  db:
    driver: local
  ui:
    driver: local
    
networks:
  default:
    driver: bridge