version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "9000:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: Drs_2022
      MYSQL_DATABASE: drsdb
    volumes:
      - ./Engine/DB/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
  app:
    build: ./
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment: 
      MYSQL_DATABASE: drsdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Drs_2022
      MYSQL_DATABASE_HOST: db
    links:
      - db
    volumes:
      - ./:/usr/src/app/
volumes:
  db:
    driver: local

networks:
  default:
    external:
      name: mynet