version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "9000:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: Drs_2022
      MYSQL_DATABASE: drsdb

  engine:
    build: 
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - ./:/usr/src/app/

networks:
  default:
    driver: bridge